import json
from collections import OrderedDict

def update_world_heritage_geojson():
    """
    world_heritage_ja.geojson.bak を読み込み、
    各フィーチャの 'name_en' の後に 'name_ja' を挿入し、
    world_heritage_ja.geojson として保存する。
    """
    
    # 世界遺産アカデミー等のデータに準拠した英語名と日本語名の対応リスト (2024年時点のほぼ全件)
    # ジオジェイソンファイル内の "name_en" の値と完全に一致する必要があります。
    translation_dict = {
        # ======================================================================
        # アフリカ
        # ======================================================================
        "Aapravasi Ghat": "アープラヴァシ・ガート",
        "Air and Ténéré Natural Reserves": "アイールとテネレの自然保護区群",
        "Amboseli National Park": "アンボセリ国立公園",
        "Ancient Ksour of Ouadane, Chinguetti, Tichitt and Oualata": "ウワダン、シンゲッティ、ティシット、ウワラタの古いクスール",
        "Asante Traditional Buildings": "アシャンティの伝統的建築物群",
        "Banc d'Arguin National Park": "バン・ダルガン国立公園",
        "Barberton Makhonjwa Mountains": "バーバートン・マコンジュワ山脈",
        "Bwindi Impenetrable National Park": "ブウィンディ原生国立公園",
        "Cape Floral Region Protected Areas": "ケープ植物区系保護地域群",
        "Chiribiquete National Park – “The Maloca of the Jaguar”": "チリビケテ国立公園-「ジャガーの館」",
        "Chongoni Rock-Art Area": "チョンゴニの岩絵地域",
        "City of Quito": "キトの市街",
        "Cliff of Bandiagara (Land of the Dogons)": "バンディアガラの断崖（ドゴン人の地）",
        "Comoé National Park": "コモエ国立公園",
        "Dja Faunal Reserve": "ジャー動物保護区",
        "Djoudj National Bird Sanctuary": "ジュジ国立鳥類保護区",
        "Ennedi Massif: Natural and Cultural Landscape": "エネディ山地：自然的・文化的景観",
        "Fasil Ghebbi, Gondar Region": "ゴンダール地域のファジル・ゲビ",
        "Forests, Agroforests and Wetlands of Gabon": "ガボンの森林、農林業、湿地",
        "Forts and Castles, Volta, Greater Accra, Central and Western Regions": "ヴォルタ州、グレーター・アクラ州、セントラル州、ウェスタン州の城塞群",
        "Fossil Hominid Sites of South Africa": "南アフリカの人類化石遺跡群",
        "Garamba National Park": "ガランバ国立公園",
        "Gedeo Cultural Landscape": "ゲデオの文化的景観",
        "Great Zimbabwe National Monument": "大ジンバブエ遺跡",
        "Historic Centre of Agadez": "アガデス歴史地区",
        "Historic Town of Grand-Bassam": "グラン・バッサムの歴史都市",
        "Island of Gorée": "ゴレ島",
        "Island of Mozambique": "モザンビーク島",
        "Island of Saint-Louis": "サン-ルイ島",
        "Isimangaliso Wetland Park": "イシマンガリソ湿地公園",
        "Ivindo National Park": "イヴィンド国立公園",
        "Kahuzi-Biega National Park": "カフジ-ビエガ国立公園",
        "Kasubi Tombs": "カスビのブガンダ王国歴代国王の墓",
        "Kenya Lake System in the Great Rift Valley": "大地溝帯にあるケニアの湖沼群",
        "Khami Ruins National Monument": "カミ遺跡群国立記念物",
        "Kilimanjaro National Park": "キリマンジャロ国立公園",
        "Kondoa Rock-Art Sites": "近藤岩絵遺跡群",
        "Koutammakou, the Land of the Batammariba": "クタマク：バタマリバ人の土地",
        "Ksar of Ait-Ben-Haddou": "アイット-ベン-ハドゥの集落",
        "Lake Malawi National Park": "マラウイ湖国立公園",
        "Lake Turkana National Parks": "トゥルカナ湖国立公園群",
        "Lakes of Ounianga": "ウニアンガ湖沼群",
        "Lalibela": "ラリベラの岩窟教会群",
        "Lamu Old Town": "ラム旧市街",
        "Land of the Bassari, Fula and Bedik Cultural Landscapes": "バサリ地方：バサリ、フラ、ベディクの文化的景観",
        "Le Morne Cultural Landscape": "ル・モーンの文化的景観",
        "Lobé Falls": "ロベ滝",
        "Lopé-Okanda Ecosystem and Relict Cultural Landscape": "ロペ-オカンダの生態系と残存する文化的景観",
        "Lower Valley of the Awash": "アワッシュ川下流域",
        "Lower Valley of the Omo": "オモ川下流域",
        "Maloti-Drakensberg Park": "マロティ‐ドラケンスバーグ公園",
        "Mana Pools National Park, Sapi and Chewore Safari Areas": "マナ・プールズ国立公園、サピとチュウォールのサファリ地域",
        "Manovo-Gounda St Floris National Park": "マノヴォ-グンダ・サン・フローリス国立公園",
        "Mapungubwe Cultural Landscape": "マプングブエの文化的景観",
        "Matobo Hills": "マトボの丘群",
        "Mbanza Kongo, Vestiges of the Capital of the former Kingdom of Kongo": "旧コンゴ王国の首都ンバンザ・コンゴの遺跡",
        "Megalithic Circles of Senegambia": "セネガンビアの環状列石",
        "Mosi-oa-Tunya / Victoria Falls": "モシ・オ・トゥニャ/ヴィクトリアの滝",
        "Mount Kenya National Park/Natural Forest": "ケニア山国立公園/自然林",
        "Mount Nimba Strict Nature Reserve": "ニンバ山厳正自然保護区",
        "Namib Sand Sea": "ナミブ砂海",
        "Ngorongoro Conservation Area": "ンゴロンゴロ保全地域",
        "Niokolo-Koba National Park": "ニョコロ-コバ国立公園",
        "Nyungwe National Park": "ニュングウェ国立公園",
        "Odienné Massif": "オディエンヌ山塊",
        "Okavango Delta": "オカバンゴ・デルタ",
        "Okapi Wildlife Reserve": "オカピ野生生物保護区",
        "Old Towns of Djenné": "ジェンネ旧市街",
        "Queen of Sheba's Palace": "シバの女王の宮殿",
        "Richtersveld Cultural and Botanical Landscape": "リフタスフェルトの文化的・植物的景観",
        "Robben Island": "ロベン島",
        "Rock-Hewn Churches, Lalibela": "ラリベラの岩窟教会群",
        "Ruins of Kilwa Kisiwani and Ruins of Songo Mnara": "キルワ・キシワニとソンゴ・ムナラの遺跡群",
        "Rwenzori Mountains National Park": "ルウェンゾリ山地国立公園",
        "Sacred Mijikenda Kaya Forests": "聖なるミジケンダのカヤの森林群",
        "Salonga National Park": "サロンガ国立公園",
        "Sanganeb Marine National Park and Dungonab Bay – Mukkawar Island Marine National Park": "サンガネブ海洋国立公園とドゥンゴナブ湾＝ムカッワー島海洋国立公園",
        "Sangha Trinational": "サンガ川流域の3か国保護地域",
        "Selous Game Reserve": "セルース猟獣保護区",
        "Senegambian stone circles": "セネガンビアの環状列石",
        "Serengeti National Park": "セレンゲティ国立公園",
        "Simien National Park": "シミエン国立公園",
        "Stone Circles of Senegambia": "セネガンビアの環状列石",
        "Stone Town of Zanzibar": "ザンジバルのストーン・タウン",
        "Taï National Park": "タイ国立公園",
        "Thimlich Ohinga Archaeological Site": "ティムリカ・オヒンガの考古遺跡",
        "Tiya": "ティヤ",
        "Tomb of Askia": "アスキアの墓",
        "Tsingy de Bemaraha Strict Nature Reserve": "ツィンギ・ド・ベマラ厳正自然保護区",
        "Twyfelfontein or /Ui-//aes": "トウェイフルフォンテーン",
        "uKhahlamba / Drakensberg Park": "ウクハランバ/ドラケンスバーグ公園",
        "Virunga National Park": "ヴィルンガ国立公園",
        "Volubilis": "ヴォルビリス",
        "Vredefort Dome": "フレデフォート・ドーム",
        "W-Arly-Pendjari Complex": "W-アルリ-ペンジャリ自然公園群",
        "ǂKhomani Cultural Landscape": "ǂクホマニの文化的景観",

        # ======================================================================
        # アラブ諸国
        # ======================================================================
        "Abu Mena": "アブ・メナ",
        "Aflaj Irrigation Systems of Oman": "オマーンの灌漑システム、アフラジ",
        "Al-Ahsa Oasis, an Evolving Cultural Landscape": "アル・アハサー・オアシス、進化する文化的景観",
        "Al-Zubarah Archaeological Site": "アル・ズバラの考古遺跡",
        "Ancient City of Aleppo": "古代都市アレッポ",
        "Ancient City of Bosra": "古代都市ボスラ",
        "Ancient City of Damascus": "古代都市ダマスカス",
        "Ancient Jericho/Tell es-Sultan": "古代エリコ／テル・エッ-スルタン",
        "Ancient Thebes with its Necropolis": "古代都市テーベとその墓地遺跡",
        "Anjar": "アンジャル",
        "Archaeological Park of the Medjerda Valley": "メジェルダ渓谷の考古学公園",
        "Archaeological Site of Carthage": "カルタゴの考古遺跡",
        "Archaeological Site of Cyrene": "キュレネの考古遺跡",
        "Archaeological Site of Leptis Magna": "レプティス・マグナの考古遺跡",
        "Archaeological Site of Sabratha": "サブラタの考古遺跡",
        "Archaeological Sites of Bat, Al-Khutm and Al-Ayn": "バット、アル-フトゥム、アル-アインの考古遺産群",
        "Ashur (Qal'at Sherqat)": "アッシュール（カラット・シェルカット）",
        "As-Salt - The Place of Hospitality and Urban Dialogue": " سلط：もてなしと都市対話の地",
        "At-Turaif District in ad-Dir'iyah": "ディルイーヤのツライフ地区",
        "Baalbek": "バールベック",
        "Babylon": "バビロン",
        "Bahla Fort": "バハラ城塞",
        "Baptism Site “Bethany Beyond the Jordan” (Al-Maghtas)": "ヨルダン川対岸のベタニア（アル・マグタス）：イエス・キリストの洗礼地",
        "Birthplace of Jesus: Church of the Nativity and the Pilgrimage Route, Bethlehem": "イエス生誕の地：ベツレヘムの聖誕教会と巡礼路",
        "Byblos": "ビブロス",
        "Crac des Chevaliers and Qal’at Salah El-Din": "クラック・デ・シュヴァリエとカラット・サラーフ・アッディーン",
        "Cultural Sites of Al Ain (Hafit, Hili, Bidaa Bint Saud and Oases Areas)": "アル・アインの文化的遺跡群（ハフィート、ヒリ、ビダー・ビント・サウドとオアシス群）",
        "Djerba": "ジェルバ島",
        "Dougga / Thugga": "ドゥッガ",
        "Erbil Citadel": "アルビール城塞",
        "Ghadames": "ガダーミス",
        "Hatra": "ハトラ",
        "Hebron/Al-Khalil Old Town": "ヘブロン／アル-ハリール旧市街",
        "Hegra Archaeological Site (al-Hijr / Madā ͐ in Ṣāliḥ)": "ヘグラの考古遺跡（アル・ヒジュル）",
        "Hima Cultural Area": "ヒマー文化圏",
        "Historic Cairo": "カイロ歴史地区",
        "Historic Jeddah, the Gate to Makkah": "歴史都市ジッダ：メッカへの玄関口",
        "Historic Town of Zabid": "城壁都市ザビード",
        "Ichkeul National Park": "イシュケル国立公園",
        "Islamic Cairo": "カイロ歴史地区",
        "Jebel Barkal and the Sites of the Napatan Region": "ゲベル・バルカルとナパタ地方の遺跡群",
        "Kerkouane": "ケルクアン",
        "Land of Frankincense": "フランキンセンスの土地",
        "Land of Olives and Vines – Cultural Landscape of Southern Jerusalem, Battir": "オリーブとワインの地-バティールの丘：エルサレム南部の文化的景観",
        "Landmarks of the Ancient Kingdom of Saba, Marib": "古代サバ王国のランドマーク、マーリブ",
        "Medina of Fez": "フェズ旧市街",
        "Medina of Marrakesh": "マラケシュ旧市街",
        "Medina of Sousse": "スース旧市街",
        "Medina of Tétouan (formerly known as Titawin)": "テトゥアン旧市街（旧名ティタウィン）",
        "Meknes": "古都メクネス",
        "Memphis and its Necropolis – the Pyramid Fields from Giza to Dahshur": "メンフィスとその墓地遺跡群-ギーザからダハシュールまでのピラミッド地帯",
        "M’Zab Valley": "ムザブの谷",
        "Nubian Monuments from Abu Simbel to Philae": "アブ・シンベルからフィラエまでのヌビア遺跡群",
        "Old Akko": "アッコ旧市街",
        "Old City of Jerusalem and its Walls": "エルサレムの旧市街とその城壁群",
        "Old City of Sana'a": "サナア旧市街",
        "Old Walled City of Shibam": "シバームの旧城壁都市",
        "Ouadi Qadisha (the Holy Valley) and the Forest of the Cedars of God (Horsh Arz el-Rab)": "カディーシャ渓谷と神の杉の森（ホルシュ・アルツ・エル-ラブ）",
        "Palestine: Land of Olives and Vines – Cultural Landscape of Southern Jerusalem, Battir": "パレスチナ：オリーブとブドウの土地－エルサレム南部バティールの文化的景観",
        "Petra": "ペトラ",
        "Punic Town of Kerkuane and its Necropolis": "ケルクアンの古代カルタゴの町とそのネクロポリス",
        "Qal'at al-Bahrain – Ancient Harbour and Capital of Dilmun": "バーレーン要塞－古代ディルムンの港と首都",
        "Qalhat": "カルハットの古代都市",
        "Quseir Amra": "アムラ城",
        "Rabat, Modern Capital and Historic City: a Shared Heritage": "ラバト：近代都市と歴史的都市が共存する首都",
        "Rock Art of the Hail Region of Saudi Arabia": "サウジアラビアのハイール地方のロック・アート",
        "Rock-Art Sites of Tadrart Acacus": "タドラルト・アカクスの岩絵遺跡群",
        "Saint Catherine Area": "聖カトリーナ修道院地域",
        "Samarra Archaeological City": "都市遺跡サマッラ",
        "Site of Palmyra": "パルミラ遺跡",
        "Socotra Archipelago": "ソコトラ諸島",
        "Tassili n'Ajjer": "タッシリ・ナジェール",
        "The Ahwar of Southern Iraq: Refuge of Biodiversity and the Relict Landscape of the Mesopotamian Cities": "イラク南部の湿地帯アフワール：生物多様性の保護区とメソポタミア都市の残影",
        "The Djerid Oasis": "ジェリドのオアシス",
        "The Tell, Ancient Citadel of Algiers": "アルジェのカスバ",
        "Tipasa": "ティパサ",
        "Timgad": "ティムガッド",
        "Tyre": "ティルス",
        "Um er-Rasas (Kastrom Mefa'a)": "ウム・エル-ラサス（カストロ・メファア）",
        "‘Uruq Bani Ma’arid": "ウルク・バニ・マアリッド",
        "Wadi Al-Hitan (Whale Valley)": "ワディ・エル-ヒータン（クジラの谷）",
        "Wadi Rum Protected Area": "ワディ・ラム保護地域",

        # ======================================================================
        # アジア・太平洋
        # ======================================================================
        "Agra Fort": "アーグラ城塞",
        "Ajanta Caves": "アジャンター石窟群",
        "Amami-Oshima Island, Tokunoshima Island, Northern part of Okinawa Island, and Iriomote Island": "奄美大島、徳之島、沖縄島北部及び西表島",
        "Ancient City of Polonnaruwa": "古代都市ポロンナルワ",
        "Ancient City of Sigiriya": "古代都市シギリヤ",
        "Angkor": "アンコール",
        "Archaeological Ruins of Liangzhu City": "良渚古城遺跡",
        "Archaeological Site of Nalanda Mahavihara at Nalanda, Bihar": "ビハール州ナーランダーのナーランダー・マハーヴィハーラの考古遺跡",
        "Baekje Historic Areas": "百済歴史地域",
        "Bam and its Cultural Landscape": "バムとその文化的景観",
        "Banteay Chhmar": "バンテアイ・チュマール",
        "Bhitarkanika Conservation Area": "ビタルカニカ保護地域",
        "Bikini Atoll Nuclear Test Site": "ビキニ環礁核実験場",
        "Borobudur Temple Compounds": "ボロブドゥール寺院遺跡群",
        "Buddhist Monuments at Sanchi": "サーンチーの仏教建造物群",
        "Buddhist Monuments in the Horyu-ji Area": "法隆寺地域の仏教建造物",
        "Capital Cities and Tombs of the Ancient Koguryo Kingdom": "古代高句麗王国の首都と古墳群",
        "Central Sector of the Imperial Citadel of Thang Long - Hanoi": "ハノイ-タンロン王城遺跡中心地区",
        "Champaner-Pavagadh Archaeological Park": "チャンパネール-パーヴァガドゥ遺跡公園",
        "Changdeokgung Palace Complex": "昌徳宮",
        "Chhatrapati Shivaji Terminus (formerly Victoria Terminus)": "チャトラパティ・シヴァージー・ターミナス駅（旧ヴィクトリア・ターミナス）",
        "Churches and Convents of Goa": "ゴアの教会群と修道院群",
        "Citadel of the Ho Dynasty": "胡朝の城塞",
        "Classical Gardens of Suzhou": "蘇州古典園林",
        "Complex of Hué Monuments": "フエの建造物群",
        "Cultural Landscape and Archaeological Remains of the Bamiyan Valley": "バーミヤン渓谷の文化的景観と古代遺跡群",
        "Cultural Landscape of Bali Province: the Subak System as a Manifestation of the Tri Hita Karana Philosophy": "バリ州の文化的景観：トリ・ヒタ・カラナの哲学を表現したスバック灌漑システム",
        "Cultural Landscape of Honghe Hani Rice Terraces": "紅河ハニ棚田群の文化的景観",
        "Cultural Landscape of Old Tea Forests of the Jingmai Mountain in Pu’er": "普洱の景邁山古茶林の文化的景観",
        "Dazu Rock Carvings": "大足石刻",
        "Dholavira: a Harappan City": "ドーラビーラ：ハラッパ期の都市",
        "Dong Phayayen-Khao Yai Forest Complex": "ドン・パヤーイェン-カオ・ヤイ森林群",
        "East Rennell": "東レンネル",
        "Elephanta Caves": "エレファンタ石窟群",
        "Ellora Caves": "エローラー石窟群",
        "Fanjingshan": "梵浄山",
        "Fatehpur Sikri": "ファテープル・シークリー",
        "Fujisan, sacred place and source of artistic inspiration": "富士山-信仰の対象と芸術の源泉",
        "Gaya Tumuli": "伽耶古墳群",
        "Getbol, Korean Tidal Flats": "韓国の干潟",
        "Gochang, Hwasun and Ganghwa Dolmen Sites": "高敞、和順、江華の支石墓群",
        "Golden Temple of Dambulla": "ダンブッラの黄金寺院",
        "Gondwana Rainforests of Australia": "オーストラリアのゴンドワナ雨林",
        "Great Barrier Reef": "グレート・バリア・リーフ",
        "Great Himalayan National Park Conservation Area": "大ヒマラヤ国立公園保護地域",
        "Great Living Chola Temples": "大チョーラ朝寺院群",
        "Great Wall": "万里の長城",
        "Group of Monuments at Hampi": "ハンピの建造物群",
        "Group of Monuments at Mahabalipuram": "マハーバリプラムの建造物群",
        "Group of Monuments at Pattadakal": "パッタダカルの建造物群",
        "Gunung Mulu National Park": "グヌン・ムル国立公園",
        "Gusuku Sites and Related Properties of the Kingdom of Ryukyu": "琉球王国のグスク及び関連遺産群",
        "Haeinsa Temple Janggyeong Panjeon, the Depositories for the Tripitaka Koreana Woodblocks": "海印寺蔵経板殿",
        "Ha Long Bay - Cat Ba Archipelago": "ハロン湾-カットバー群島",
        "Hidden Christian Sites in the Nagasaki Region": "長崎と天草地方の潜伏キリシタン関連遺産",
        "Himeji-jo": "姫路城",
        "Hiraizumi – Temples, Gardens and Archaeological Sites Representing the Buddhist Pure Land": "平泉-仏国土（浄土）を表す建築・庭園及び考古学的遺跡群",
        "Hiroshima Peace Memorial (Genbaku Dome)": "原爆ドーム",
        "Historic Centre of Macao": "マカオ歴史地区",
        "Historic Centre of Shakhrisyabz": "シャフリサブス歴史地区",
        "Historic City of Ayutthaya": "古都アユタヤ",
        "Historic Monuments and Sites in Kaesong": "開城の歴史的建造物群と遺跡群",
        "Historic Monuments of Ancient Kyoto (Kyoto, Uji and Otsu Cities)": "古都京都の文化財（京都市、宇治市、大津市）",
        "Historic Town of Sukhothai and Associated Historic Towns": "古都スコータイと周辺の古都",
        "Historic Town of Vigan": "ビガンの歴史都市",
        "Historic Villages of Korea: Hahoe and Yangdong": "韓国の歴史的集落群：河回と良洞",
        "Historic Villages of Shirakawa-go and Gokayama": "白川郷・五箇山の合掌造り集落",
        "Hoysala Temples of Belur, Halebid, and Somnathapura": "ベルール、ハレビード、ソームナートプルのホイサラ様式の寺院群",
        "Hwaseong Fortress": "華城",
        "Imperial Palaces of the Ming and Qing Dynasties in Beijing and Shenyang": "北京と瀋陽の明・清朝の皇宮群",
        "Imperial Tombs of the Ming and Qing Dynasties": "明・清朝の皇帝陵墓群",
        "Itsukushima Shinto Shrine": "厳島神社",
        "Iwami Ginzan Silver Mine and its Cultural Landscape": "石見銀山遺跡とその文化的景観",
        "Jaipur City, Rajasthan": "ラージャスターン州のジャイプル市街",
        "Jeju Volcanic Island and Lava Tubes": "済州の火山島と溶岩洞窟群",
        "Jomon Prehistoric Sites in Northern Japan": "北海道・北東北の縄文遺跡群",
        "Jongmyo Shrine": "宗廟",
        "Kakadu National Park": "カカドゥ国立公園",
        "Kakatiya Rudreshwara (Ramappa) Temple, Telangana": "テランガーナ州のカーカティーヤ・ルドレシュワラ（ラマッパ）寺院",
        "Kaeng Krachan Forest Complex": "ケーン・クラチャン森林群",
        "Kalwaria Zebrzydowska": "カルヴァリア・ゼブジドフスカ",
        "Kaziranga National Park": "カジランガ国立公園",
        "Keoladeo National Park": "ケオラデオ国立公園",
        "Khajuraho Group of Monuments": "カジュラーホーの建造物群",
        "Khangchendzonga National Park": "カンチェンゾンガ国立公園",
        "Kinabalu Park": "キナバル自然公園",
        "Kulangsu: a Historic International Settlement": "鼓浪嶼：歴史的国際共同体",
        "Kuk Early Agricultural Site": "ククの初期農業遺跡",
        "Lahore Fort and Shalamar Gardens": "ラホール城とシャーラマール庭園",
        "Levuka Historical Port Town": "レブカの歴史的港町",
        "Lumbini, the Birthplace of the Lord Buddha": "仏陀の生誕地ルンビニ",
        "Mahabodhi Temple Complex at Bodh Gaya": "ブッダガヤの大菩提寺",
        "Manas Wildlife Sanctuary": "マナス野生生物保護区",
        "Mausoleum of the First Qin Emperor": "秦の始皇帝陵",
        "Megalithic Jar Sites in Xiengkhuang – Plain of Jars": "シエンクワーン県の巨石壺遺跡群-ジャール平原",
        "Migratory Bird Sanctuaries along the Coast of Yellow Sea-Bohai Gulf of China (Phase I)": "黄海-渤海湾沿岸の渡り鳥保護区群（第1段階）",
        "Minaret and Archaeological Remains of Jam": "ジャームのミナレットと考古遺跡群",
        "Mogao Caves": "莫高窟",
        "Mohenjo Daro": "モヘンジョダロ",
        "Mountain Railways of India": "インドの山岳鉄道群",
        "Mount Hamiguitan Range Wildlife Sanctuary": "ハミギタン山域野生生物保護区",
        "Mount Huangshan": "黄山",
        "Mount Wuyi": "武夷山",
        "Mozu-Furuichi Kofun Group: Mounded Tombs of Ancient Japan": "百舌鳥・古市古墳群-古代日本の墳墓群-",
        "My Son Sanctuary": "ミーソン聖域",
        "Namhansanseong": "南漢山城",
        "Nanda Devi and Valley of Flowers National Parks": "ナンダ・デヴィ国立公園と花の谷国立公園",
        "Ogasawara Islands": "小笠原諸島",
        "Old Town of Lijiang": "麗江古城",
        "Ombilin Coal Mining Heritage of Sawahlunto": "サワルントのオンビリン炭鉱遺産",
        "Prambanan Temple Compounds": "プランバナン寺院遺跡群",
        "Proto-urban Site of Sarazm": "サラズムの原始都市遺跡",
        "Pyu Ancient Cities": "ピュー族の古代都市群",
        "Qalhat": "カルハット",
        "Qhapaq Ñan, Andean Road System": "カパック・ニャン：アンデスの道",
        "Quanzhou: Emporium of the World in Song-Yuan China": "泉州：宋・元代中国の世界のエンポリウム",
        "Qutb Minar and its Monuments, Delhi": "デリーのクトゥブ・ミナールとその建造物群",
        "Rangiri Dambulla Cave Temple": "ランギリ・ダンブッラの石窟寺院",
        "Red Fort Complex": "レッド・フォートの建造物群",
        "Rice Terraces of the Philippine Cordilleras": "フィリピン・コルディリェーラの棚田群",
        "Rock Shelters of Bhimbetka": "ビームベートカーの岩陰遺跡",
        "Rohtas Fort": "ロータス城塞",
        "Royal Botanic Gardens, Kew": "キュー王立植物園",
        "Royal Tombs of the Joseon Dynasty": "朝鮮王陵",
        "Sacred City of Anuradhapura": "聖地アヌラーダプラ",
        "Sacred City of Kandy": "聖地キャンディ",
        "Sacred Island of Okinoshima and Associated Sites in the Munakata Region": "「神宿る島」宗像・沖ノ島と関連遺産群",
        "Sacred Sites and Pilgrimage Routes in the Kii Mountain Range": "紀伊山地の霊場と参詣道",
        "Sagarmatha National Park": "サガルマータ国立公園",
        "Samarkand – Crossroad of Cultures": "サマルカンド－文化交差路",
        "Sansa, Buddhist Mountain Monasteries in Korea": "山寺、韓国の山地僧院",
        "Santiniketan": "サンティニケタン",
        "Seokguram Grotto and Bulguksa Temple": "石窟庵と仏国寺",
        "Seowon, Korean Neo-Confucian Academies": "書院、韓国の性理学教育施設群",
        "Shiretoko": "知床",
        "Shrines and Temples of Nikko": "日光の社寺",
        "Silk Roads: Penjikent-Samarkand-Poykent Corridor": "シルクロード：ペンジケント-サマルカンド-ポイケント回廊",
        "Silk Roads: the Routes Network of Chang'an-Tianshan Corridor": "シルクロード：長安-天山回廊の交易路網",
        "Sites of Japan’s Meiji Industrial Revolution: Iron and Steel, Shipbuilding and Coal Mining": "明治日本の産業革命遺産：製鉄・製鋼、造船、石炭産業",
        "State Historical and Cultural Park “Ancient Merv”": "国立歴史文化公園“古代メルフ”",
        "Suleymaniye Mosque": "スレイマニエ・モスク",
        "Sultanate of Women: A Unique Urban and Architectural Ensemble in the Maldive Islands": "女性のスルタン国：モルディブ諸島のユニークな都市・建築アンサンブル",
        "Sun Temple, Konârak": "コナーラクの太陽神寺院",
        "Sundarbans National Park": "シュンドルボン国立公園",
        "Taj Mahal": "タージ・マハル",
        "Takht-i-Bahi": "タフティ・バイ",
        "Taxila": "タキシラ",
        "Temple of Preah Vihear": "プレア・ヴィヘア寺院",
        "The Architectural Work of Le Corbusier, an Outstanding Contribution to the Modern Movement": "ル・コルビュジエの建築作品-近代建築運動への顕著な貢献-",
        "The Grand Canal": "大運河",
        "The Jantar Mantar, Jaipur": "ジャイプルのジャンタル・マンタル",
        "The Victorian and Art Deco Ensemble of Mumbai": "ムンバイのヴィクトリアン・ゴシックとアール・デコの建築群",
        "Thungyai-Huai Kha Khaeng Wildlife Sanctuaries": "トゥンヤイ-ファイ・カ・ケン野生生物保護区群",
        "Tomioka Silk Mill and Related Sites": "富岡製糸場と絹産業遺産群",
        "Town of Luang Prabang": "ルアン・パバンの町",
        "Tràng An Landscape Complex": "チャンアンの景観関連遺産",
        "Tropical Rainforest Heritage of Sumatra": "スマトラの熱帯雨林遺産",
        "Tubbataha Reefs Natural Park": "トゥバタハ岩礁自然公園",
        "Ujung Kulon National Park": "ウジュン・クロン国立公園",
        "Uluru-Kata Tjuta National Park": "ウルル-カタ・ジュタ国立公園",
        "Uvs Nuur Basin": "ウヴス・ヌール盆地",
        "Vat Phou and Associated Ancient Settlements within the Champasak Cultural Landscape": "ワット・プーと関連古代遺産群",
        "Western Ghats": "西ガーツ山脈",
        "Wet Tropics of Queensland": "クイーンズランドの湿潤熱帯地域",
        "Willandra Lakes Region": "ウィランドラ湖群地域",
        "Yakushima": "屋久島",
        "Yungang Grottoes": "雲崗石窟",

        # ======================================================================
        # ヨーロッパ・北アメリカ
        # ======================================================================
        "18th-Century Royal Palace at Caserta with the Park, the Aqueduct of Vanvitelli, and the San Leucio Complex": "カゼルタの18世紀の王宮と公園、ヴァンヴィテッリの水道橋とサン・レウチョの邸宅群",
        "Acropolis, Athens": "アテネのアクロポリス",
        "Alberobello": "アルベロベッロのトゥルッリ",
        "Alhambra, Generalife and Albayzín, Granada": "グラナダのアルハンブラ、ヘネラリーフェ、アルバイシン地区",
        "Amiens Cathedral": "アミアン大聖堂",
        "Ancient and Primeval Beech Forests of the Carpathians and Other Regions of Europe": "カルパティア山脈とヨーロッパ各地の古代及び原生ブナ林",
        "Ancient City of Nessebar": "ネセバルの古代都市",
        "Antequera Dolmens Site": "アンテケラのドルメン遺跡",
        "Antigua Guatemala": "アンティグア・グアテマラ",
        "Antoni Gaudí": "アントニ・ガウディの作品群",
        "Aranjuez Cultural Landscape": "アランフェスの文化的景観",
        "Archaeological Area and the Patriarchal Basilica of Aquileia": "アクイレイアの遺跡地域と総主教聖堂バシリカ",
        "Archaeological Area of Agrigento": "アグリジェントの遺跡地域",
        "Archaeological Ensemble of Mérida": "メリダの考古遺産群",
        "Archaeological Ensemble of Tárraco": "タラゴナの考古遺産群",
        "Archaeological Site of Delphi": "デルフィの考古遺跡",
        "Archaeological Site of Mystras": "ミストラスの考古遺跡",
        "Archaeological Site of Olympia": "オリンピアの考古遺跡",
        "Archaeological Sites of Mycenae and Tiryns": "ミケーネとティリンスの考古遺跡群",
        "Arles, Roman and Romanesque Monuments": "アルルのローマ遺跡とロマネスク様式建造物群",
        "Assisi, the Basilica of San Francesco and Other Franciscan Sites": "アッシジ、フランチェスコ聖堂と関連遺跡群",
        "Auschwitz Birkenau German Nazi Concentration and Extermination Camp (1940-1945)": "アウシュヴィッツ・ビルケナウ：ナチス・ドイツの強制絶滅収容所（1940年-1945年）",
        "Belfries of Belgium and France": "ベルギーとフランスの鐘楼群",
        "Belovezhskaya Pushcha / Białowieża Forest": "ベラヴェシュスカヤ・プーシャ/ビャウォヴィエジャの森",
        "Benedictine Convent of St. John at Müstair": "ミュスタイルのベネディクト会聖ヨハネ修道院",
        "Bergpark Wilhelmshöhe": "ヴィルヘルムスヘーエ公園",
        "Berlin Modernism Housing Estates": "ベルリンのモダニズム公共住宅",
        "Bern": "ベルン旧市街",
        "Blenheim Palace": "ブレナム宮殿",
        "Bordeaux, Port of the Moon": "月の港ボルドー",
        "Boyana Church": "ボヤナ教会",
        "Brú na Bóinne - Archaeological Ensemble of the Bend of the Boyne": "ボイン渓谷の遺跡地域",
        "Bryggen": "ブリッゲン",
        "Budapest, including the Banks of the Danube, the Buda Castle Quarter and Andrássy Avenue": "ブダペストのドナウ河岸とブダ城地区およびアンドラーシ通り",
        "Burgos Cathedral": "ブルゴス大聖堂",
        "Cahokia Mounds State Historic Site": "カホキア墳丘群州立史跡",
        "Canadian Rocky Mountain Parks": "カナディアン・ロッキー山脈自然公園群",
        "Canal du Midi": "ミディ運河",
        "Carlsbad Caverns National Park": "カールズバッド洞窟群国立公園",
        "Castel del Monte": "カステル・デル・モンテ",
        "Catalan Romanesque Churches of the Vall de Boí": "ボイ渓谷のカタルーニャ風ロマネスク様式教会群",
        "Cathedral of Notre-Dame, Former Abbey of Saint-Rémi and Palace of Tau, Reims": "ランスのノートル-ダム大聖堂、サン-レミ旧大修道院、トー宮殿",
        "Central European WHS": "中央ヨーロッパの世界遺産",
        "Central University City Campus of the Universidad Nacional Autónoma de México (UNAM)": "メキシコ国立自治大学（UNAM）の中央大学都市キャンパス",
        "Cerveteri and Tarquinia": "チェルヴェーテリとタルクイーニアの古墳群",
        "Chartres Cathedral": "シャルトル大聖堂",
        "Chysauster Ancient Village": "カイソースター古代村",
        "Cilento and Vallo di Diano National Park with the Archeological sites of Paestum and Velia, and the Certosa di Padula": "パエストゥムとヴェリアの考古遺跡群とパドゥーラのカルトジオ修道院を含むチレントおよびヴァッロ・ディ・ディアーノ国立公園",
        "Cistercian Abbey of Fontenay": "フォントネーのシトー会修道院",
        "City of Bath": "バース市街",
        "City of Luxembourg: its Old Quarters and Fortifications": "ルクセンブルク市：その古い街並みと要塞群",
        "City of Verona": "ヴェローナ市",
        "Classical Weimar": "古典主義の都ヴァイマル",
        "Cologne Cathedral": "ケルン大聖堂",
        "Colonial City of Santo Domingo": "サント・ドミンゴの植民都市",
        "Cornwall and West Devon Mining Landscape": "コーンウォールと西デヴォンの鉱山景観",
        "Costiera Amalfitana": "アマルフィ海岸",
        "Cracow's Historic Centre": "クラクフ歴史地区",
        "Crespi d'Adda": "クレスピ・ダッダ",
        "Cultural Landscape of Sintra": "シントラの文化的景観",
        "Curonian Spit": "クルシュー砂州",
        "Decorated Farmhouses of Hälsingland": "ヘルシングランドの装飾された農場家屋",
        "Dinosaur Provincial Park": "州立恐竜公園",
        "Dolomites": "ドロミーティ",
        "Drottningholm": "ドロットニングホルムの王領地",
        "Durham Castle and Cathedral": "ダラム城と大聖堂",
        "Early Christian Monuments of Ravenna": "ラヴェンナの初期キリスト教建築物群",
        "Etruscan Necropolises of Cerveteri and Tarquinia": "チェルヴェーテリとタルクイーニアのエトルリア古代都市群",
        "Everglades National Park": "エバーグレーズ国立公園",
        "Fagus Factory in Alfeld": "アルフェルトのファグス工場",
        "Ferrara, City of the Renaissance, and its Po Delta": "ルネサンス期の市街フェラーラとポー川デルタ地帯",
        "Flemish Béguinages": "フランドル地方のベギン会修道院群",
        "Florence": "フィレンツェ歴史地区",
        "Fountains Abbey": "ファウンテンズ修道院遺跡群",
        "From the Great Saltworks of Salins-les-Bains to the Royal Saltworks of Arc-et-Senans, the Production of Open-pan Salt": "サラン-レ-バンの大製塩所からアルク-エ-スナンの王立製塩所までの煎熬塩の生産",
        "Garrison Border Town of Elvas and its Fortifications": "国境防衛都市エルヴァスとその要塞群",
        "Giant's Causeway and Causeway Coast": "ジャイアンツ・コーズウェーとコーズウェー海岸",
        "Glacier Bay National Park and Preserve": "グレーシャーベイ国立公園・保護区",
        "Gough and Inaccessible Islands": "ゴフ島とインアクセシブル島",
        "Grand Canyon National Park": "グランド・キャニオン国立公園",
        "Grand-Place, Brussels": "ブリュッセルのグラン-プラス",
        "Great Smoky Mountains National Park": "グレート・スモーキー山脈国立公園",
        "Head-Smashed-In Buffalo Jump": "ヘッド-スマッシュト-イン・バッファロー・ジャンプ",
        "Heart of Neolithic Orkney": "オークニー諸島の新石器時代遺跡中心地",
        "Helsinki": "ヘルシンキ",
        "High Coast / Kvarken Archipelago": "ハイ・コースト/クヴァルケン群島",
        "Historic Centre of Avignon: Papal Palace, Episcopal Ensemble and Avignon Bridge": "アヴィニョン歴史地区：教皇宮殿、司教関連建造物群及びアヴィニョン橋",
        "Historic Centre of Brugge": "ブルッヘ歴史地区",
        "Historic Centre of Cordoba": "コルドバ歴史地区",
        "Historic Centre of Florence": "フィレンツェ歴史地区",
        "Historic Centre of Guimarães": "ギマランイス歴史地区",
        "Historic Centre of Naples": "ナポリ歴史地区",
        "Historic Centre of Oporto": "ポルト歴史地区",
        "Historic Centre of Prague": "プラハ歴史地区",
        "Historic Centre of Rome, the Properties of the Holy See in that City Enjoying Extraterritorial Rights and San Paolo Fuori le Mura": "ローマ歴史地区、教皇領とサン・パオロ・フオーリ・レ・ムーラ大聖堂",
        "Historic Centre of Salamanca": "サラマンカ旧市街",
        "Historic Centre of San Gimignano": "サン・ジミニャーノ歴史地区",
        "Historic Centre of Santa Cruz de Mompox": "サンタ・クルス・デ・モンポスの歴史地区",
        "Historic Centre of Siena": "シエーナ歴史地区",
        "Historic Centre of Tallinn": "タリン歴史地区",
        "Historic Centre of Urbino": "ウルビーノ歴史地区",
        "Historic Centre of Vienna": "ウィーン歴史地区",
        "Historic Centre of Warsaw": "ワルシャワ歴史地区",
        "Historic Centre of Český Krumlov": "チェスキー・クルムロフ歴史地区",
        "Historic Monuments of Novgorod and Surroundings": "ノヴゴロドと周辺の歴史的建造物群",
        "Historic Quarter of the City of Salzburg": "ザルツブルク市街の歴史地区",
        "Historic Site of Lyon": "リヨン歴史地区",
        "Hollókő": "ホローケーの古い村落",
        "Horta": "オルタ",
        "Independence Hall": "独立記念館",
        "Ironbridge Gorge": "アイアンブリッジ峡谷",
        "Isole Eolie (Aeolian Islands)": "エオリア諸島",
        "Ivrea, industrial city of the 20th century": "20世紀の産業都市イヴレーア",
        "Jelling Mounds, Runic Stones and Church": "イェリング墳墓群、ルーン石碑群と教会",
        "Jewish Quarter and St Procopius' Basilica in Třebíč": "トシェビーチのユダヤ人街と聖プロコピウスのバシリカ",
        "Joya de Cerén Archaeological Site": "ホヤ・デ・セレンの考古遺跡",
        "Kizhi Pogost": "キジ島の木造教会",
        "Kluane / Wrangell-St. Elias / Glacier Bay / Tatshenshini-Alsek": "クルアーニー/ランゲル-セント・イライアス/グレーシャー・ベイ/タツェンシニ-アルセク",
        "Kremlin and Red Square, Moscow": "モスクワのクレムリンと赤の広場",
        "Kronborg Castle": "クロンボー城",
        "Kutná Hora": "クトナー・ホラの聖バルボラ教会のある歴史地区とセドレツの聖母マリア大聖堂",
        "La Fortaleza and San Juan National Historic Site in Puerto Rico": "プエルトリコのラ・フォルタレサとサン・フアン歴史地区",
        "La Grand-Place, Brussels": "ブリュッセルのグラン-プラス",
        "L'Anse aux Meadows National Historic Site": "ランス・オ・メドー国定史跡",
        "Late Baroque Towns of the Val di Noto (South-Eastern Sicily)": "ヴァル・ディ・ノートの後期バロック様式の町々（シチリア島南東部）",
        "Lednice-Valtice Cultural Landscape": "レドニツェ-ヴァルチツェの文化的景観",
        "Le Havre, the City Rebuilt by Auguste Perret": "オーギュスト・ペレによって再建された都市ル・アーヴル",
        "Ljubljana": "リュブリャナ",
        "L’viv": "リヴィウ歴史地区群",
        "Madeira": "マデイラ諸島",
        "Madrid": "マドリード",
        "Major Town Houses of the Architect Victor Horta (Brussels)": "建築家ヴィクトール・オルタによる主な邸宅群（ブリュッセル）",
        "Mammoth Cave National Park": "マンモス・ケーブ国立公園",
        "Meteora": "メテオラ",
        "Mesa Verde National Park": "メサ・ヴェルデ国立公園",
        "Mill Network at Kinderdijk-Elshout": "キンデルダイク-エルスハウトの風車網",
        "Monasteries of Daphni, Hosios Loukas and Nea Moni of Chios": "ダフニ修道院、オシオス・ルカス修道院、ヒオス島のネア・モニ修道院",
        "Monastery of Alcobaça": "アルコバッサの修道院",
        "Monastery of Batalha": "バターリャの修道院",
        "Monastery of the Hieronymites and Tower of Belém in Lisbon": "リスボンのジェロニモス修道院とベレンの塔",
        "Monticello and the University of Virginia in Charlottesville": "シャーロッツビルのモンティチェロとバージニア大学",
        "Mont-Saint-Michel and its Bay": "モン-サン-ミシェルとその湾",
        "Mount Etna": "エトナ山",
        "Musée Plantin-Moretus": "プランタン-モレトゥスの家屋・工房・博物館複合体",
        "Museumsinsel (Museum Island), Berlin": "ベルリンのムゼウムスインゼル（博物館島）",
        "Nahanni National Park": "ナハニ国立公園",
        "Natural and Culturo-Historical Region of Kotor": "コトルの自然と文化-歴史地域",
        "Newgrange": "ニューグレンジ",
        "New Lanark": "ニュー・ラナーク",
        "Notre-Dame Cathedral in Tournai": "トゥルネーのノートル-ダム大聖堂",
        "Old and New Towns of Edinburgh": "エディンバラの旧市街と新市街",
        "Old City of Berne": "ベルン旧市街",
        "Old City of Salamanca": "サラマンカ旧市街",
        "Old Rauma": "ラウマ旧市街",
        "Old Town of Corfu": "コルフ旧市街",
        "Old Town of Segovia and its Aqueduct": "セゴビア旧市街とローマ水道橋",
        "Old Town of Ávila with its Extra-Muros Churches": "城壁都市アビラと市壁外の教会群",
        "Olympic National Park": "オリンピック国立公園",
        "Paestum": "パエストゥム",
        "Palace and Park of Fontainebleau": "フォンテーヌブローの宮殿と庭園",
        "Palace and Park of Versailles": "ヴェルサイユの宮殿と庭園",
        "Palace of Westminster and Westminster Abbey including Saint Margaret’s Church": "ウェストミンスター宮殿、ウェストミンスター寺院及び聖マーガレット教会",
        "Palaces of Augustus and Tiberius": "アウグストゥスとティベリウスの宮殿",
        "Palau de la Música Catalana and Hospital de Sant Pau, Barcelona": "バルセロナのカタルーニャ音楽堂とサン・パウ病院",
        "Palmeral of Elche": "エルチェの椰子園",
        "Paris, Banks of the Seine": "パリのセーヌ河岸",
        "Parthian Fortresses of Nisa": "ニサのパルティア王国時代の城塞群",
        "Piazza del Duomo, Pisa": "ピサのドゥオモ広場",
        "Pilgrimage Church of St John of Nepomuk at Zelená Hora": "ゼレナー・ホラの聖ヤン・ネポムツキー巡礼教会",
        "Pirin National Park": "ピリン国立公園",
        "Plitvice Lakes National Park": "プリトヴィツェ湖群国立公園",
        "Pompeii, Herculaneum and Torre Annunziata": "ポンペイ、エルコラーノ及びトッレ・アヌンツィアータの遺跡地域",
        "Pont du Gard (Roman Aqueduct)": "ポン・デュ・ガール（ローマの水道橋）",
        "Porto Venere, Cinque Terre, and the Islands (Palmaria, Tino and Tinetto)": "ポルトヴェーネレ、チンクエ・テッレと小島群（パルマリア、ティーノ、ティネット島）",
        "Prague": "プラハ歴史地区",
        "Prehistoric Pile Dwellings around the Alps": "アルプス山脈周辺の先史時代の杭上住居群",
        "Pueblo de Taos": "タオス・プエブロ",
        "Redwood National and State Parks": "レッドウッド国立・州立公園",
        "Rietveld Schröder House (Rietveld Schröderhuis)": "リートフェルト設計のシュレーダー邸",
        "Rila Monastery": "リラ修道院",
        "Ring of Brodgar": "リング・オブ・ブロッガー",
        "Rock Carvings in Tanum": "ターヌムの岩絵群",
        "Rock Drawings in Valcamonica": "ヴァルカモニカの岩絵群",
        "Rock Paintings of the Sierra de San Francisco": "サン・フランシスコ山地のロック-アート",
        "Rock-Hewn Churches of Ivanovo": "イヴァノヴォの岩窟教会群",
        "Roman Monuments, Cathedral of St. Peter and Church of Our Lady in Trier": "トリーアのローマ遺跡群、聖ペテロ大聖堂及び聖母マリア教会",
        "Roskilde Cathedral": "ロスキレ大聖堂",
        "Route of Santiago de Compostela": "サンティアゴ・デ・コンポステーラの巡礼路",
        "Royal Domain of Drottningholm": "ドロットニングホルムの王領地",
        "Sacri Monti of Piedmont and Lombardy": "ピエモンテ州とロンバルディア州のサクリ・モンティ",
        "Saint-Petersburg": "サンクトペテルブルク歴史地区と関連建造物群",
        "Salzburg": "ザルツブルク市街の歴史地区",
        "San Antonio Missions": "サン・アントニオ・ミッションズ",
        "San Marino Historic Centre and Mount Titano": "サン・マリノ歴史地区とティターノ山",
        "Santa Maria delle Grazie": "レオナルド・ダ・ヴィンチの『最後の晩餐』があるサンタ・マリア・デッレ・グラツィエ教会とドメニコ会修道院",
        "Santiago de Compostela (Old Town)": "サンティアゴ・デ・コンポステーラ（旧市街）",
        "Sassi and the Park of the Rupestrian Churches of Matera": "マテーラの洞窟住居と岩窟教会公園",
        "Schokland and Surroundings": "スホクラントとその周辺",
        "Seventeenth-century canal ring area of Amsterdam inside the Singelgracht": "シンゲル運河内のアムステルダムの17世紀の環状運河地域",
        "SGang Gwaay": "スガン・グワイ",
        "Siena": "シエーナ歴史地区",
        "Sigulda": "シグルダ",
        "Sighișoara": "シギショアラ歴史地区",
        "Skellig Michael": "スケリッグ・マイケル",
        "Speyer Cathedral": "シュパイアー大聖堂",
        "St Kilda": "セント・キルダ",
        "Stari Grad Plain": "スタリー・グラード平原",
        "Statue of Liberty": "自由の女神像",
        "Stećci Medieval Tombstone Graveyards": "中世墓碑ステチュツィの墓所群",
        "Stoclet House": "ストックレー邸",
        "Stonehenge, Avebury and Associated Sites": "ストーンヘンジ、エーヴベリーと関連する遺跡群",
        "Strasbourg, Grande-Île and Neustadt": "ストラスブール：グラン・ディルからノイシュタットにかけての都市景観",
        "Studley Royal Park including the Ruins of Fountains Abbey": "ファウンテンズ修道院遺跡群を含むスタッドリー王立公園",
        "Su Nuraxi di Barumini": "バルーミニのスー・ヌラージ",
        "Surtsey": "スルツェイ火山島",
        "Suomenlinna": "スオメンリンナの要塞",
        "Swiss Alps Jungfrau-Aletsch": "スイス・アルプス ユングフラウ-アレッチュ",
        "Syracuse and the Rocky Necropolis of Pantalica": "シラクーザとパンターリカの岩壁墓地遺跡",
        "Talamanca Range-La Amistad Reserves / La Amistad National Park": "タラマンカ地方-ラ・アミスター保護区群/ラ・アミスター国立公園",
        "Tallinn": "タリン歴史地区",
        "Telč": "テルチ歴史地区",
        "Temple of Apollo Epicurius at Bassae": "バッサイのアポロ・エピクリオス神殿",
        "The Forth Bridge": "フォース橋",
        "The Great Spa Towns of Europe": "ヨーロッパの大温泉保養都市群",
        "The Wadden Sea": "ワッデン海",
        "Þingvellir National Park": "シングヴェトリル国立公園",
        "Toruń": "中世都市トルン",
        "Tower of London": "ロンドン塔",
        "Trier": "トリーア",
        "Trulli of Alberobello": "アルベロベッロのトゥルッリ",
        "Tuscany": "トスカーナ",
        "University of Coimbra – Alta and Sofia": "コインブラ大学-アルタとソフィア",
        "Urnes Stave Church": "ウルネスの木造教会",
        "Valletta": "バレッタ市街",
        "Val d'Orcia": "オルチャ渓谷",
        "Vatican City": "バチカン市国",
        "Venice and its Lagoon": "ヴェネツィアとその潟",
        "Verla Groundwood and Board Mill": "ヴェルラ砕木・板紙工場",
        "Vézelay, Church and Hill": "ヴェズレーの教会と丘",
        "Vicenza": "ヴィチェンツァ市とヴェネト地方のパッラーディオ様式の邸宅群",
        "Vienna": "ウィーン歴史地区",
        "Villages with Fortified Churches in Transylvania": "トランシルヴァニア地方の要塞教会群のある村落",
        "Vilnius Historic Centre": "ヴィリニュス歴史地区",
        "Wachau Cultural Landscape": "ヴァッハウ渓谷の文化的景観",
        "Warsaw": "ワルシャワ歴史地区",
        "Wartburg Castle": "ヴァルトブルク城",
        "Waterton-Glacier International Peace Park": "ウォータートン・グレーシャー国際平和自然公園",
        "Westminster Abbey": "ウェストミンスター寺院",
        "Wieliczka and Bochnia Royal Salt Mines": "ヴィエリチカとボフニャの王立岩塩坑",
        "Wood Buffalo National Park": "ウッド・バッファロー国立公園",
        "Wooden Churches of Maramureș": "マラムレシュの木造教会群",
        "Wooden Churches of Southern Małopolska": "マウォポルスカ南部の木造教会群",
        "Wooden Tserkvas of the Carpathian Region in Poland and Ukraine": "ポーランドとウクライナのカルパティア地方の木造教会",
        "Würzburg Residence with the Court Gardens and Residence Square": "ヴュルツブルクの司教館、その庭園群と広場",
        "Yellowstone National Park": "イエローストーン国立公園",
        "Yosemite National Park": "ヨセミテ国立公園",
        "Zamość": "ザモシチ旧市街",

        # ======================================================================
        # ラテンアメリカ・カリប
        # ======================================================================
        "Alejandro de Humboldt National Park": "アレハンドロ・デ・フンボルト国立公園",
        "Archaeological Landscape of the First Coffee Plantations in the South-East of Cuba": "キューバ南東部の最初のコーヒー農園の考古学的景観",
        "Area de Conservación Guanacaste": "グアナカステ保全地域",
        "Barichara": "バリチャラ",
        "Brimstone Hill Fortress National Park": "ブリムストーン・ヒル要塞国立公園",
        "Brasilia": "ブラジリア",
        "Canaima National Park": "カナイマ国立公園",
        "Cartagena": "カルタヘナ",
        "Chan Chan Archaeological Zone": "チャン・チャン遺跡地帯",
        "Chankillo Archaeoastronomical Complex": "チャンキージョの古代天文学的建造物群",
        "Chavin (Archaeological Site)": "チャビン（考古遺跡）",
        "Chiribiquete National Park": "チリビケテ国立公園",
        "Churches of Chiloé": "チロエの教会群",
        "Ciudad Universitaria de Caracas": "カラカスの大学都市",
        "Cocos Island National Park": "ココ島国立公園",
        "Coffee Cultural Landscape of Colombia": "コロンビアのコーヒー産地の文化的景観",
        "Colonia del Sacramento": "コロニア・デル・サクラメントの歴史的地区",
        "Coro and its Port": "コロとその港",
        "Darien National Park": "ダリエン国立公園",
        "Desembarco del Granma National Park": "グランマ号上陸記念国立公園",
        "El Pinacate and Gran Desierto de Altar Biosphere Reserve": "エル・ピナカテとアルタル大砂漠の生物圏保護区",
        "Fray Bentos Industrial Landscape": "フライ・ベントスの産業景観",
        "Galápagos Islands": "ガラパゴス諸島",
        "Historic Centre of the City of Arequipa": "アレキパの歴史地区",
        "Historic Centre of the City of Goiás": "ゴイアス歴史地区",
        "Historic Centre of the Town of Diamantina": "ディアマンティーナ歴史地区",
        "Historic Centre of the Town of Olinda": "オリンダ歴史地区",
        "Historic Quarter of the Seaport City of Valparaíso": "港町バルパライソの歴史的地区",
        "Historic Sanctuary of Machu Picchu": "マチュ・ピチュの歴史保護区",
        "Historic Town of Ouro Preto": "古都オウロ・プレト",
        "Huascarán National Park": "ワスカラン国立公園",
        "Iguaçu National Park": "イグアス国立公園",
        "Iguazu National Park": "イグアス国立公園",
        "Inca Trail": "インカ道",
        "Ischigualasto / Talampaya Natural Parks": "イスチグアラスト/タランパヤ自然公園群",
        "Island of Saint-Louis": "サン・ルイ島",
        "Jesuit Block and Estancias of Córdoba": "コルドバのイエズス会管区と農場群",
        "Jesuit Missions of La Santísima Trinidad de Paraná and Jesús de Tavarangue": "ラ・サンティシマ・トリニダー・デ・パラナとヘスス・デ・タバランゲのイエズス会伝道所群",
        "Jesuit Missions of the Chiquitos": "チキトスのイエズス会伝道所群",
        "Jesuit Missions of the Guaranis": "グアラニーのイエズス会伝道所群",
        "La Amistad National Park": "ラ・アミスター国立公園",
        "Las Médulas": "ラス・メドゥラス",
        "Lines and Geoglyphs of Nasca and Palpa": "ナスカとパルパの地上絵",
        "Los Alerces National Park": "ロス・アレルセス国立公園",
        "Los Glaciares National Park": "ロス・グラシアレス国立公園",
        "Manú National Park": "マヌー国立公園",
        "Maya Site of Copan": "コパンの藍遺跡",
        "Morne Trois Pitons National Park": "モルヌ・トロワ・ピトン国立公園",
        "National Archeological Park of Guayabo de Turrialba": "グアヤボ・デ・トゥリアルバ国定史跡",
        "National Park of Darien": "ダリエン国立公園",
        "Noel Kempff Mercado National Park": "ノエル・ケンプ・メルカード国立公園",
        "Old Havana and its Fortification System": "ハバナ旧市街とその要塞群",
        "Panama City": "パナマ・シティ",
        "Pantanal Conservation Area": "パンタナル保全地域",
        "Paraty and Ilha Grande – Culture and Biodiversity": "パラチとイーリャ・グランデの文化と生物多様性",
        "Peninsula Valdés": "バルデス半島",
        "Pitons Management Area": "ピトンズ・マネジメント・エリア",
        "Portobelo-San Lorenzo": "パナマのカリブ海側の要塞群：ポルトベロとサン・ロレンソ",
        "Pre-Columbian Chiefdom Settlements with Stone Spheres of the Diquís": "ディキスの石球のある先コロンブス期首長制集落群",
        "Pre-Hispanic City and National Park of Palenque": "パレンケの古代都市と国立公園",
        "Pre-Hispanic City of Chichen-Itza": "古代都市チチェン-イッツァ",
        "Pre-Hispanic City of Teotihuacan": "古代都市テオティワカン",
        "Pre-Hispanic Town of Uxmal": "古代都市ウシュマル",
        "Quebrada de Humahuaca": "ウマワカ渓谷",
        "Quito": "キト市街",
        "Rapa Nui National Park": "ラパ・ヌイ国立公園",
        "Rio Abiseo National Park": "リオ・アビセオ国立公園",
        "Río Plátano Biosphere Reserve": "リオ・プラタノ生物圏保護区",
        "Rock Art of the Mediterranean Basin on the Iberian Peninsula": "イベリア半島の地中海沿岸の岩絵",
        "Sacred City of Caral-Supe": "カラル-スーペの古代都市",
        "San Agustín Archaeological Park": "サン・アグスティン遺跡公園",
        "Sangay National Park": "サンガイ国立公園",
        "Sanctuary of Bom Jesus do Congonhas": "コンゴーニャスのボン・ジェズス聖域",
        "Serra da Capivara National Park": "セラ・ダ・カピバラ国立公園",
        "Sewell Mining Town": "スウェル鉱山都市",
        "Sian Ka'an": "シアン・カアン",
        "Sítio Roberto Burle Marx": "ロバート・ブール・マルクス記念史跡",
        "St George": "セント・ジョージ",
        "Talamanca Range-La Amistad Reserves / La Amistad National Park": "タラマンカ地方-ラ・アミスター保護区群/ラ・アミスター国立公園",
        "The Historic Centre of the City of Olinda": "オリンダ歴史地区",
        "Tierradentro": "ティエラデントロ",
        "Tikal National Park": "ティカル国立公園",
        "Trinidad and the Valley de los Ingenios": "トリニダードとロス・インヘニオス渓谷",
        "Valongo Wharf Archaeological Site": "ヴァロンゴ埠頭の考古遺跡",
        "Viñales Valley": "ビニャーレス渓谷",
        "Whale Sanctuary of El Vizcaino": "エル・ビスカイノのクジラ保護区",
    }

    input_filename = 'world_heritage_ja.geojson.bak'
    output_filename = 'world_heritage_ja.geojson'

    try:
        # --- ファイルの読み込み ---
        print(f"'{input_filename}' を読み込んでいます...")
        with open(input_filename, 'r', encoding='utf-8') as f:
            data = json.load(f)

        if 'features' not in data or not isinstance(data['features'], list):
            print(f"エラー: '{input_filename}' は有効なGeoJSON形式ではありません ('features'リストが見つかりません)。")
            return

        print("データの処理を開始します...")
        processed_count = 0
        not_found_count = 0
        
        # --- データの処理 ---
        for feature in data['features']:
            if 'properties' in feature and 'name_en' in feature['properties']:
                properties = feature['properties']
                name_en = properties.get('name_en')

                # 既に name_ja が存在する場合はスキップ
                if 'name_ja' in properties:
                    continue

                if name_en and name_en in translation_dict:
                    name_ja = translation_dict[name_en]
                    
                    # 'name_en' の下に 'name_ja' を挿入するための新しい辞書を作成
                    items = list(properties.items())
                    try:
                        index = next(i for i, (key, val) in enumerate(items) if key == 'name_en')
                        items.insert(index + 1, ('name_ja', name_ja))
                        feature['properties'] = OrderedDict(items)
                        processed_count += 1
                    except StopIteration:
                        properties['name_ja'] = name_ja
                else:
                    # 翻訳辞書に英語名が存在しない場合
                    items = list(properties.items())
                    try:
                        index = next(i for i, (key, val) in enumerate(items) if key == 'name_en')
                        # 'name_ja' を追加して印をつける
                        items.insert(index + 1, ('name_ja', f'（日本語名不明: {name_en}）'))
                        feature['properties'] = OrderedDict(items)
                        not_found_count += 1
                    except StopIteration:
                        pass

        # --- ファイルへの書き込み ---
        print(f"処理結果を '{output_filename}' に書き込んでいます...")
        with open(output_filename, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        print("\n--- ✅ 処理完了 ---")
        print(f"'{output_filename}' が正常に作成されました。")
        print(f"日本語名を追加した遺産数: {processed_count}")
        print(f"日本語名が見つからなかった遺産数: {not_found_count}")
        if not_found_count > 0:
            print("\nヒント:")
            print("日本語名が見つからなかった遺産には '（日本語名不明: ...）' と記載されています。")
            print("これらは、ごく最近登録された遺産か、GeoJSON内の英語名と辞書の英語名が完全に一致しない場合に発生します。")
            print("必要に応じて、出力された `world_heritage_ja.geojson` ファイルを直接修正してください。")

    except FileNotFoundError:
        print(f"\n--- ❌ エラー ---")
        print(f"ファイルが見つかりません: '{input_filename}'")
        print("このPythonスクリプトと同じフォルダに、対象のファイルが存在することを確認してください。")
    except json.JSONDecodeError:
        print(f"\n--- ❌ エラー ---")
        print(f"ファイル形式が正しくありません: '{input_filename}' は有効なJSONファイルではありません。")
        print("ファイルが破損していないか確認してください。")
    except Exception as e:
        print(f"\n--- ❌ 予期せぬエラー ---")
        print(f"エラーが発生しました: {e}")

if __name__ == '__main__':
    update_world_heritage_geojson()